site_name: PoktBot
theme: material
plugins:
    - search
    - macros
repo_url: https://github.com/cryptonglab/poktbot
extra:
    version: 0.1.2
    project_name: PoktBot
    project_name_lowercase: poktbot